### ISSUE TITLE
[run_travis] AttributeError: 'list' object has no attribute 'proc'

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#262]
With #261 I'm running `run_travis` and getting error.

```
$ roscd swri_profiler
$ git branch -vv
* master 71ae85e [origin/master] Merge pull request #11 from pjreed/install-files
$ git log -1
commit 71ae85e1956a1e10b5d73502015205e15c55f384
Merge: b15c768 54607db
Author: P. J. Reed <pjreed@users.noreply.github.com>
Date:   Thu Nov 2 14:24:24 2017 -0500

    Merge pull request #11 from pjreed/install-files
    
    Install Python scripts & HTML files

$ ~/industrial_ci/industrial_ci/scripts/run_travis
Job 1: ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Job 2: ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
run all with /home/n130s/industrial_ci/industrial_ci/scripts/run_travis -
$ 
$ ~/industrial_ci/industrial_ci/scripts/run_travis .
Job 1: ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Job 2: ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
run all with /home/n130s/industrial_ci/industrial_ci/scripts/run_travis -
$ ~/industrial_ci/industrial_ci/scripts/run_travis -
Running job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Testing /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler
ROS distro '' is not supported
Tests failed exit code '1'
Failed job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Traceback (most recent call last):
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 170, in <module>
    main(os.path.abspath(os.path.dirname(__file__)), sys.argv)
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 167, in main
    sys.exit(bash.proc)
AttributeError: 'list' object has no attribute 'proc'

$ ~/industrial_ci/industrial_ci/scripts/run_travis . -
Running job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Testing /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler
ROS distro '' is not supported
Tests failed exit code '1'
Failed job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Traceback (most recent call last):
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 170, in <module>
    main(os.path.abspath(os.path.dirname(__file__)), sys.argv)
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 167, in main
    sys.exit(bash.proc)
AttributeError: 'list' object has no attribute 'proc'
```

**Comment by ipa-mdl** [comment]
I guess I have replaced something by accident.
Apart from this issue, you need to set `ROS_DISTRO`.
