### ISSUE TITLE
[run_travis] "TypeError: sequence item 1: expected string, dict found"

### ISSUE THREAD

**Issue by 130s** [ros-industrial/industrial_ci#293]
```
$ cd industrial_ci
$ git log -1
commit 1eaffcfb291c1d3d5ebb631c1c07100e0fb4302f
Merge: cba6908 e373080
Author: Isaac I.Y. Saito <130s@users.noreply.github.com>
Date:   Thu Jun 28 19:12:58 2018 -0700

    Merge pull request #292 from ipa-mdl/debian-stretch
    
    test for debian stretch instead of jessie
$ ./industrial_ci/scripts/run_travis -h                                                                            
Traceback (most recent call last):
  File "./industrial_ci/scripts/run_travis", line 174, in <module>
    main(os.path.abspath(os.path.dirname(__file__)), sys.argv)
  File "./industrial_ci/scripts/run_travis", line 143, in main
    global_env, job_envs = read_env(read_yaml(path)['env'])
  File "./industrial_ci/scripts/run_travis", line 91, in read_env
    g = ' '.join(env['global'])
TypeError: sequence item 1: expected string, dict found

$ ll
total 128K
drwxrwxr-x  8 n130s n130s 4.0K Jul  1 03:22 .git/
drwxrwxr-x  5 n130s n130s 4.0K Jul  1 02:48 ./
-rw-rw-r--  1 n130s n130s 6.9K Jul  1 02:48 .travis.yml
drwxrwxr-x  2 n130s n130s 4.0K Jul  1 02:48 doc/
drwxrwxr-x  5 n130s n130s 4.0K Jul  1 02:48 industrial_ci/
-rw-rw-r--  1 n130s n130s 1.2K Jul  1 02:48 .gitlab-ci.yml
-rw-rw-r--  1 n130s n130s 5.3K Jul  1 02:48 README.rst
-rwxrwxr-x  1 n130s n130s 1.6K Jun 22 22:00 gitlab.sh*
-rwxrwxr-x  1 n130s n130s 1.2K Jun 12 19:45 travis.sh*
-rw-rw-r--  1 n130s n130s   83 Jun 12 19:45 .ci.rosinstall.jade
-rwxrwxr-x  1 n130s n130s 1.1K Jun 12 19:45 ci.sh*
-rw-rw-r--  1 n130s n130s  12K Jun 12 19:45 LICENSE
-rw-rw-r--  1 n130s n130s  179 Jun 12 19:45 .travis.rosinstall
drwxrwxr-x 27 n130s n130s 4.0K Nov  2  2017 ../
```

**Comment by machinekoder** [comment]
I start working on this issue for #wrid18
