### ISSUE TITLE
Prerelease fails to resolve pip key

### ISSUE THREAD

**Issue by wxmerkt** [ros-industrial/industrial_ci#770]
Hi, I am using a pip key in my package.xml as a test_depend. However, the pre-release tests now fail with:
```
  Identified the following build dependencies (ignoring packages available from source):
    - catkin
[...]
  Resolved the dependencies to the following binary packages:
 [...]
  Identified the following run and test dependencies (ignoring packages available from source):
 [...]
    **- python3-trimesh-pip**
  Resolved the dependencies to the following binary packages:
    **- trimesh**
  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/apt/cache.py", line 299, in __getitem__
      rawpkg = self._cache[key]
  KeyError: 'trimesh'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 304, in <module>
      main()
    File "/tmp/ros_buildfarm/scripts/devel/create_devel_task_generator.py", line 152, in main
      get_binary_package_versions(apt_cache, debian_pkg_names_testing))
    File "/tmp/ros_buildfarm/ros_buildfarm/common.py", line 175, in get_binary_package_versions
      pkg = apt_cache[debian_pkg_name]
    File "/usr/lib/python3/dist-packages/apt/cache.py", line 301, in __getitem__
      raise KeyError('The cache has no package named %r' % key)
  KeyError: "The cache has no package named 'trimesh'"
  'sudo -EH -u ci sh -c . /opt/ros/noetic/setup.sh && cd '/tmp/tmp.dOdWxB7CzJ' && exec ./prerelease.sh -y' returned with 1
'run_prerelease_script' returned with code '1' after 1 min 26 sec
```

Obviously `rosdep resolve python3-trimesh-pip` resolves to
```
#pip
trimesh
```

Is this an issue with resolving pip dependencies? Or is this an issue with a stale cache? (This is on GitHub Actions)

**Comment by mathias-luedtke** [comment]
The prerelease test uses ros_buildfarm, which does not support pip (https://github.com/ros-infrastructure/ros_buildfarm/issues/895).
